### ISSUE TITLE
Setup Wordpress on developer machines

### ISSUE THREAD

**Issue by aiwilliams** [wfth/wordpress#1]
We're on a path to "spike" content upload and delivery. Keep the end users in mind as you evaluate things: the website visitor looking for sermons and the producer/content manager who will publish the content. Our goal is to make their lives better with technology!

The first thing we need to do is get Wordpress running on our laptops as quickly as possible. We are assuming it is going to work well in the end so we will also invest a little bit in making the process repeatable. Of course we always have the goal of learning as we go!

1. Vagrant from Hashicorp. This is a powerful tool for defining virtual machine configurations. It provides a Vagrantfile, much like a Gemfile, so that a project can maintain one or more virtual machines that support development environment maintenance (it can also support production environments!).
2. Find a Vagrant "box" that is already configured with the latest Wordpress. This would be ideal, the fastest path to a running Wordpress. We don't care much about how to setup Wordpress. I expect we'll use Dreamhost in production.
3. Explore Wordpress to see what is possible for media distribution (upload/storage, presentation/search, streaming audio, etc). There may be a lot built-in that will help us re-create the Sermons screens from wisdomonline.org.
4. Explore plugins that fill in the gaps you discover in 3. There may be no gaps, or we may need to build something from scratch.

**Comment by isaacjwilliams** [comment]
[The Wordpress Download Manager](http://www.wpdownloadmanager.com/) looks amazing for sermon downloading (and uploading!). Not to mention its very authoritative name!

**Comment by isaacjwilliams** [comment]
For streaming sermons, we can use Wordpress's built-in mp3 player. Or, if we want more features (E.G. fast-forward, rewind, loop, album art), we can use WonderPlugin's [WordPress Audio Player Plugin](https://www.wonderplugin.com/wordpress-audio-player/). I don't know how complicated we want to make it though, or if we need any extra features.

**Comment by isaacjwilliams** [comment]
For setting up a throwaway Wordpress environment, [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV) (Varying Vagrant Vagrants) hits the spot. Don't try using it on Windows, though; VirtualBox networking doesn't play well with Microsoft.
