### ISSUE TITLE
Investigate whether a resource catalog and shopping cart can be implemented

### ISSUE THREAD

**Issue by aiwilliams** [wfth/wordpress#2]
Administrators need to be able to upload resources for sale and visitors need to be able to add them to a cart and purchase them. Be sure to walk through the process on the current site and collect a list of features that appear to be supported. I wonder if the features change when someone is logged in on the site? It is not necessary that the new site work *exactly* like the existing site but it is helpful to know what will be lost or gained in the move.

**Comment by isaacjwilliams** [comment]
**Current feature list**

- Basic cart with "Continue Shopping" and quantity options
- Two payment options
    - "Pay with Credit Card" (accepts credit card numbers in a basic `input` tag, with no iframe! :scream:)
    - "Pay with Paypal"

**Comment by isaacjwilliams** [comment]
Looks like we need to use [WooCommerce](https://woocommerce.com/). WooCommerce has been downloaded by 19,208,667 people and powers over 39% of all online stores! The UI is simple, appealing, and intuitive. It supports PayPal, Stripe, mailing checks, and a few other payment methods.
