### ISSUE TITLE
Look for a theme suitable for a website

### ISSUE THREAD

**Issue by aiwilliams** [wfth/wordpress#3]
There are lots of themes for blogs. Are there any good themes for a website? Of course the administrators will still need a Post function for releasing new Series and there is a News page on the current site that looks like a blog. Having a few options is always appreciated and will help to narrow the customer's preferences down.

**Comment by isaacjwilliams** [comment]
### [SeaSun](https://wordpress.org/themes/seasun/)

Very simple and highly customizable, SeaSun is a pretty theme that can be used for almost anything (excepting, perhaps, an online store).

![image](https://cloud.githubusercontent.com/assets/1526445/21570305/e1358b00-ce92-11e6-9461-f3e5563ad3df.png)


![image](https://cloud.githubusercontent.com/assets/1526445/21570297/c73c2ccc-ce92-11e6-90c9-24d56610c2a5.png)

**Comment by isaacjwilliams** [comment]
### [Responsive](https://wordpress.org/themes/responsive/)

This theme is basic, but that means it'll be easy to hack. :grin: Responsive comes with widgets (similar to those of gty.org) and supports an image slider.

![image](https://cloud.githubusercontent.com/assets/1526445/21570572/35b22baa-ce95-11e6-92b3-5e621d899b8d.png)

![image](https://cloud.githubusercontent.com/assets/1526445/21570582/57191f60-ce95-11e6-861d-82c00fd549b5.png)

**Comment by isaacjwilliams** [comment]
### [Accelerate](https://themegrill.com/themes/accelerate/)

Accelerate is highly customizable, with widgets and built in a slider, but you have to pay to get the latest version. Simple and beautiful.

![image](https://cloud.githubusercontent.com/assets/1526445/21571531/53c13768-ce9e-11e6-9c9b-2c67a7e9c822.png)

![image](https://cloud.githubusercontent.com/assets/1526445/21571543/7156b8ca-ce9e-11e6-9604-5def7dab028e.png)

**Comment by isaacjwilliams** [comment]
After a bit of discussion, we believe that Responsive is our best bet. Praise the cyber chimps!
