### ISSUE TITLE
Investigate a way to collect names/addresses for monthly mailing

### ISSUE THREAD

**Issue by aiwilliams** [wfth/wordpress#5]
Perhaps I should sign up myself and see if there are two systems for purchasing and donating.

**Comment by isaacjwilliams** [comment]
I signed up for Wisdom Online. The features are quite basic.

- Viewing and updating basic account information ("My Information")
- Accessing purchased downloads ("My Downloads")
- Saving payment information (address, email, name)

**Comment by isaacjwilliams** [comment]
It seems as if WooCommerce supports all of these features. Wahoo!
